# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 319cb2db80a7c8fefc6418336f8c34990bf0e925789aaed263cdf61166a94d77aa563d9bbdd0df479536c3a13097986ce0f6e7e8b8fe03c77738ef352915d30b

test:
  secret_key_base: 580a70babe877e3eb5296654223c3b1ca7bc020e06d5686165ecb69dd4a9fb1321da39c8f42214d06466449ce614bcf2b3d0ceea7599d3360d80ec7a9f19fd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
